import { test, expect, type Page } from '@playwright/test';
test.describe.configure({ retries: 0 }); test.setTimeout(90_000);
const categories=['Langley ED Shifts','RCF Additional Duty','USAF','USACS and Moonlighting','Certification, Credentials and Continuing Education','Relationship / Wife','Fun','Vacation and Leave','Health','Admin','Requested Day Off','Moving Logistics','Family','Holidays','Residency'].map((label,i)=>({id:`c${i}`,label,color:['#2563eb','#16a34a','#dc2626','#9333ea'][i%4]}));
const event=(id:string,date:string,title:string,index=0)=>({id,date,endDate:date,title,category:`c${index%categories.length}`,projectId:null,timeStatus:index<3?'all-day':'timed',startTime:index<3?null:`${String(7+Math.floor((index-3)/2)).padStart(2,'0')}:${index%2?'30':'00'}`,endTime:index<3?null:'23:00',color:categories[index%categories.length].color,notes:null,displayPriority:4,showInGrid:true,showInExport:true,linkedTaskIds:[],aiNotes:null,sourceNotes:null});
const dense=Array.from({length:34},(_,i)=>event(`dense-${i}`,'2026-08-31',i===33?'An intentionally exceptional prose title that demonstrates final-line bounded fitting without changing every agenda card geometry':i===4?'Drop off Natalie before Chicago trip':`Operational event ${i+1}`,i));
const seed={events:[...dense,event('future','2026-09-24','Future custom appointment',1),event('sep-first','2026-09-01','September first',2),event('sep-last','2026-09-30','September last',3),event('outside','2026-10-01','Outside month',4)],tasks:[],personEvents:[],people:[],milestones:[],categories,projects:[{id:'p1',name:'Project One',color:'#2563eb',order:0,aliases:[],status:'active',notes:null}]};

test.beforeEach(async({page})=>{await page.clock.setFixedTime(new Date('2026-08-31T12:00:00'));await page.addInitScript(data=>{if(!localStorage.getItem('lifegrid_store_v5'))localStorage.setItem('lifegrid_store_v5',JSON.stringify({activeCalendarId:'v0529',calendars:[{id:'v0529',name:'Operational Calendar',createdAt:'2026-08-31T12:00:00.000Z',data}]}));},seed);await page.goto('/#grid');await expect(page.getByTestId('grid-content')).toHaveAttribute('aria-busy','false');});
const open=async(page:Page,preset?:string)=>{if(await page.locator('[data-testid=panel-export-options],[data-testid=panel-export-mobile]').count()===0)await page.getByTestId('button-export').click();if(preset)await page.getByTestId(`export-date-preset-${preset}`).click();};
const generate=async(page:Page)=>{await page.getByTestId('button-export-generate').click();await expect(page.getByTestId('grid-export-status')).toHaveAttribute('data-export-status','ready',{timeout:45_000});const image=page.getByTestId('export-preview-image');await expect(image).toBeVisible();const info=await image.evaluate((n:HTMLImageElement)=>({w:n.naturalWidth,h:n.naturalHeight,src:n.src}));expect(info.w).toBeGreaterThan(0);expect(info.h).toBeGreaterThan(0);expect(info.src).toMatch(/^data:image\/png;base64,/);const bytes=Buffer.from(info.src.split(',')[1],'base64');expect([...bytes.subarray(0,8)]).toEqual([137,80,78,71,13,10,26,10]);return info;};

test('full defaults reset on every newly opened export session',async({page})=>{await open(page);const presets=page.locator('[data-testid^="export-date-preset-"]');await expect(presets).toHaveText(['Current Grid','Calendar Year','CY Q1','CY Q2','CY Q3','CY Q4','CY Current Month','Next 30','Next 14','Next 7','Today','Custom']);await expect(page.getByTestId('export-date-preset-currentGrid')).toHaveAttribute('aria-pressed','true');await expect(page.getByText('All',{exact:true}).last()).toHaveClass(/bg-primary/);await expect(page.getByTestId('select-export-project')).toHaveValue('all');await expect(page.getByRole('checkbox',{name:'Include generated timestamp'})).toBeChecked();const textInputs=page.locator('[data-testid^="panel-export"] input[type=text]');await expect(textInputs).toHaveCount(2);await expect(textInputs.nth(0)).toHaveValue('');await expect(textInputs.nth(1)).toHaveValue('');await page.getByTestId('export-date-preset-custom').click();await page.getByTestId('input-export-start').fill('2026-09-24');await page.getByTestId('input-export-end').fill('2026-09-24');await page.getByTestId('export-theme-control').getByRole('button',{name:'Dark'}).click();await page.getByRole('button',{name:'Close'}).last().click();await open(page);await expect(page.getByTestId('export-date-preset-currentGrid')).toHaveAttribute('aria-pressed','true');await expect(page.getByTestId('export-theme-control').getByRole('button',{name:'Light'})).toHaveAttribute('aria-pressed','true');await expect(page.getByTestId('input-export-start')).toHaveCount(0);await expect(page.getByTestId('export-preview')).toHaveCount(0);await expect(page.getByTestId('grid-export-status')).toHaveAttribute('data-export-error-code','');});

test('Next 7, Next 14 and Next 30 are chronological rolling grids with real PNGs',async({page})=>{for(const [preset,count,rows] of [['next7',7,1],['next14',14,2],['next30',30,5]] as const){await open(page,preset);const root=page.getByTestId('targeted-export-grid');await expect(root).toHaveAttribute('data-publication-layout','rolling-day-grid');await expect(root).toHaveAttribute('data-publication-start','2026-08-31');const cells=root.locator('[data-testid^="targeted-export-day-"]');await expect(cells).toHaveCount(count);expect((await cells.first().getAttribute('data-testid'))).toContain('2026-08-31');await expect(root.locator('tbody tr')).toHaveCount(rows);await expect(root.locator('thead th')).toHaveText(['Mon','Tue','Wed','Thu','Fri','Sat','Sun']);const dates=await cells.locator('[data-publication-date=true]').evaluateAll(nodes=>nodes.map(n=>({text:n.textContent?.trim(),overflow:getComputedStyle(n).textOverflow})));expect(dates.every(d=>d.text&&d.overflow!=='ellipsis')).toBe(true);const png=await generate(page);expect(png.w/png.h).toBeGreaterThan(1.15);await page.getByTestId('button-export-close').click();}});

test('Today and future custom day use complete agenda cards in real PNG',async({page},testInfo)=>{await open(page,'today');const root=page.getByTestId('targeted-export-grid');await expect(root).toHaveAttribute('data-publication-layout','day-agenda');await expect(root).toHaveAttribute('data-publication-event-count','34');await expect(root.locator('article[data-source-event-id]')).toHaveCount(34);expect(await root.locator('article[data-source-event-id]').evaluateAll(nodes=>new Set(nodes.map(n=>n.getAttribute('data-source-event-id'))).size)).toBe(34);await expect(root.locator('[data-publication-agenda-column="1"] article').first()).toContainText('Operational event 1');const cardPoint=await root.locator('article[data-source-event-id="dense-0"]').evaluate((card,rootNode)=>{const a=card.getBoundingClientRect(),r=(rootNode as HTMLElement).getBoundingClientRect();return{x:a.left-r.left+a.width/2,y:a.top-r.top+a.height/2,width:(rootNode as HTMLElement).scrollWidth,height:(rootNode as HTMLElement).scrollHeight};},await root.elementHandle());const agendaPng=await generate(page);const sampled=await page.evaluate(async({src,point})=>{const image=new Image();image.src=src;await image.decode();const canvas=document.createElement('canvas');canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;const context=canvas.getContext('2d')!;context.drawImage(image,0,0);return [...context.getImageData(Math.floor(point.x*image.naturalWidth/point.width),Math.floor(point.y*image.naturalHeight/point.height),1,1).data];},{src:agendaPng.src,point:cardPoint});expect(sampled[3]).toBe(255);expect(sampled.slice(0,3)).not.toEqual([255,255,255]);await expect(page.getByTestId('grid-export-status')).toHaveAttribute('data-export-renderer',testInfo.project.name==='firefox'?'canvas2d':/html-to-image|html2canvas/);await page.getByTestId('button-export-close').click();await open(page,'custom');await page.getByTestId('input-export-start').fill('2026-09-24');await page.getByTestId('input-export-end').fill('2026-09-24');await expect(root).toHaveAttribute('data-publication-layout','day-agenda');await expect(root.getByRole('heading',{name:/Thursday, September 24, 2026/})).toBeAttached();await expect(root.getByText('Future custom appointment')).toBeAttached();await generate(page);});

test('exact September month is Sunday-first and publication themes ignore app theme',async({page})=>{await page.getByTestId('button-theme-toggle').click();await expect(page.locator('html')).toHaveClass(/dark/);await open(page,'custom');await page.getByTestId('input-export-start').fill('2026-09-01');await page.getByTestId('input-export-end').fill('2026-09-30');const root=page.getByTestId('targeted-export-grid');await expect(root).toHaveAttribute('data-publication-layout','month-matrix');await expect(root.locator('thead th')).toHaveText(['Sun','Mon','Tue','Wed','Thu','Fri','Sat']);await expect(root.locator('tbody tr').first().locator('td')).toHaveCount(7);await expect(root.locator('tbody tr').first().locator('td').nth(2)).toContainText('Sep1');await expect(root.getByText('Outside month')).toHaveCount(0);const light=await root.evaluate(n=>getComputedStyle(n).backgroundColor);expect(light).toMatch(/rgb\((255|25[0-5])/);await generate(page);await expect(page.locator('html')).toHaveClass(/dark/);await page.getByTestId('button-export-close').click();await page.getByTestId('export-theme-control').getByRole('button',{name:'Dark'}).click();await expect(root).toHaveAttribute('data-publication-theme','dark');const dark=await root.evaluate(n=>getComputedStyle(n).backgroundColor);expect(dark).not.toBe(light);await generate(page);await expect(page.locator('html')).toHaveClass(/dark/);});


test('CY Current Month and routing boundaries retain deterministic families',async({page})=>{await page.clock.setFixedTime(new Date('2026-09-15T12:00:00'));await page.reload();await expect(page.getByTestId('grid-content')).toHaveAttribute('aria-busy','false');await open(page,'currentMonth');const targeted=page.getByTestId('targeted-export-grid');await expect(targeted).toHaveAttribute('data-publication-layout','month-matrix');await expect(targeted).toHaveAttribute('data-publication-start','2026-09-01');await expect(targeted).toHaveAttribute('data-publication-end','2026-09-30');await expect(targeted.locator('thead th')).toHaveText(['Sun','Mon','Tue','Wed','Thu','Fri','Sat']);await generate(page);await page.getByTestId('button-export-close').click();await open(page,'custom');await page.getByTestId('input-export-start').fill('2026-09-15');await page.getByTestId('input-export-end').fill('2026-10-29');await expect(targeted).toHaveAttribute('data-publication-layout','rolling-day-grid');await page.getByTestId('input-export-end').fill('2026-11-13');await page.getByTestId('button-export-generate').click();await expect(page.locator('[data-publication-ready=true][data-publication-layout=month-columns]')).toBeAttached({timeout:15_000});await expect(page.getByTestId('grid-export-status')).toHaveAttribute('data-export-status','ready',{timeout:45_000});});

test('dark export also remains independent from a light application',async({page})=>{await expect(page.locator('html')).not.toHaveClass(/dark/);await open(page,'next7');await page.getByTestId('export-theme-control').getByRole('button',{name:'Dark'}).click();const root=page.getByTestId('targeted-export-grid');await expect(root).toHaveAttribute('data-publication-theme','dark');expect(await root.evaluate(n=>getComputedStyle(n).backgroundColor)).toMatch(/rgb\((?:[0-5]?\d|[0-9]),/);await generate(page);await expect(page.locator('html')).not.toHaveClass(/dark/);});
