export type ReviewFinding = { key: string; recordType: string; severity: string; blocking?: boolean; calendarId?: string };
export type ReviewFilters = { recordType?: string; severity?: string };
export type ReviewSession = { calendarId: string; initialIssueKeys: string[]; currentIssueKey: string | null; resolvedIssueKeys: string[]; skippedIssueKeys: string[]; deferredIssueKeys: string[]; unavailableIssueKeys: string[]; remainingIssueKeys: string[]; startedAt: string; newIssueKeys: string[] };
export function buildReviewQueue(findings: readonly ReviewFinding[], calendarId: string, filters: ReviewFilters = {}): string[] { const seen = new Set<string>(); return findings.filter(f => (!f.calendarId || f.calendarId === calendarId) && (!filters.recordType || filters.recordType === 'both' || f.recordType === filters.recordType) && (!filters.severity || filters.severity === 'both' || (filters.severity === 'blocking' ? !!f.blocking : !f.blocking))).map(f => f.key).filter(k => !seen.has(k) && !!seen.add(k)); }
export function startReviewSession(findings: readonly ReviewFinding[], calendarId: string, filters?: ReviewFilters): ReviewSession { const keys = buildReviewQueue(findings, calendarId, filters); return { calendarId, initialIssueKeys: keys, currentIssueKey: keys[0] ?? null, resolvedIssueKeys: [], skippedIssueKeys: [], deferredIssueKeys: [], unavailableIssueKeys: [], remainingIssueKeys: keys, startedAt: new Date().toISOString(), newIssueKeys: [] }; }
function advance(s: ReviewSession, key: string, field: 'resolvedIssueKeys'|'skippedIssueKeys'|'deferredIssueKeys'|'unavailableIssueKeys'): ReviewSession { const remainingIssueKeys=s.remainingIssueKeys.filter(k=>k!==key); const values=[...new Set([...s[field],key])]; return {...s,[field]:values,remainingIssueKeys,currentIssueKey:remainingIssueKeys[0]??null}; }
export const resolveIssue=(s:ReviewSession,key:string)=>advance(s,key,'resolvedIssueKeys'); export const skipIssue=(s:ReviewSession,key:string)=>advance(s,key,'skippedIssueKeys'); export const deferIssue=(s:ReviewSession,key:string)=>advance(s,key,'deferredIssueKeys');
export function reconcileReviewSession(s: ReviewSession, findings: readonly ReviewFinding[], calendarId: string): ReviewSession { if (s.calendarId !== calendarId) return {...s,currentIssueKey:null,remainingIssueKeys:[]}; const keys=new Set(findings.map(f=>f.key)); const unavailable=s.remainingIssueKeys.filter(k=>!keys.has(k)); let next=s; unavailable.forEach(k=>next=advance(next,k,'unavailableIssueKeys')); const newIssueKeys=findings.map(f=>f.key).filter(k=>!next.initialIssueKeys.includes(k)&&!next.newIssueKeys.includes(k)); return {...next,newIssueKeys:[...next.newIssueKeys,...newIssueKeys]}; }
export const reviewTotals=(s:ReviewSession)=>({ total:s.initialIssueKeys.length, resolved:s.resolvedIssueKeys.length, skipped:s.skippedIssueKeys.length, deferred:s.deferredIssueKeys.length, unavailable:s.unavailableIssueKeys.length, remaining:s.remainingIssueKeys.length, reviewed:s.resolvedIssueKeys.length+s.skippedIssueKeys.length+s.deferredIssueKeys.length+s.unavailableIssueKeys.length });
