import test from 'node:test'; import assert from 'node:assert/strict';
import { parseAIUpdate } from '../.test-build/lib/aiPrompt.js';
import { applyPatchAtomically, getPatchReadiness } from '../.test-build/lib/aiPatchApply.js';
import { patchProposalKey } from '../.test-build/lib/aiDependencies.js';
const data=()=>({categories:[{id:'other',label:'Other',color:'#666'}],people:[],projects:[],tasks:[],events:[],personEvents:[],milestones:[]});
const envelope=(events={add:[],update:[]})=>JSON.stringify({lifegridPatchVersion:4,categories:{add:[],update:[]},people:{add:[],update:[]},projects:{add:[],update:[]},tasks:{add:[],update:[]},events,peopleSchedule:{add:[],update:[]},warnings:[]});
test('v4 event normalization preserves all-day temporal fields and recurring group',()=>{const p=parseAIUpdate(envelope({add:[{id:'evt-rel-planning-review-2026',date:'2026-12-15',endDate:'2026-12-15',title:'Relationship planning review',category:'other',timeStatus:'all-day',startTime:null,endTime:null,color:'#65a30d',notes:null,displayPriority:2,showInGrid:true,showInExport:true,eventKind:'reminder',linkedTaskIds:[],aiNotes:null,sourceNotes:null,recurringGroupId:'series-1'}],update:[]}),data().categories,data());const e=p.events.add[0];assert.equal(e.timeStatus,'all-day');assert.equal(e.endDate,'2026-12-15');assert.equal(e.recurringGroupId,'series-1');assert.equal(applyPatchAtomically(data(),p).data.events[0].timeStatus,'all-day');});
test('explicit invalid timeStatus and malformed JSON guidance are actionable',()=>{assert.throws(()=>parseAIUpdate(envelope({add:[{id:'e',date:'2026-01-01',title:'Valid title',category:'other',timeStatus:'allDay',startTime:null,endTime:null}],update:[]}),data().categories,data()),/events.timeStatus/);assert.throws(()=>parseAIUpdate('{“lifegridPatchVersion”:4,}',data().categories,data()),/could not be safely normalized/);assert.throws(()=>parseAIUpdate('PASTE_ALL_OF_YOUR_EXISTING_TASK_OBJECTS_HERE',data().categories,data()),/placeholder/);});
test('29 selected project/task proposals remain ready and apply atomically',()=>{const patch={projects:{add:[{id:'proj-relationship-future-planning-20260718',name:'Future planning',color:'#123456',order:0,aliases:[],status:'active',notes:null}],update:[]},tasks:{add:[],update:[]}};const ids=['task-rel-relationship-logistics','task-rel-event-actions','task-rel-military-career','task-rel-housing-future','task-rel-long-term-timeline'];for(let i=0;i<28;i++)patch.tasks.add.push({id:ids[i]??`task-rel-${i}`,name:`Fictional task ${i}`,category:'other',dueDate:null,status:'todo',owner:'Me',nextAction:null,notes:null,priority:'medium',projectId:'proj-relationship-future-planning-20260718',dueDateType:'project-subtask',triageStatus:'ready',parentTaskId:null,linkedEventIds:[]});const selected=new Set([patchProposalKey('projects','add',patch.projects.add[0].id),...patch.tasks.add.map(x=>patchProposalKey('tasks','add',x.id))]);const ready=getPatchReadiness(data(),patch,selected);assert.equal(ready.selectedCount,29);assert.equal(ready.canApply,true);const result=applyPatchAtomically(data(),patch);assert.equal(result.appliedKeys.length,29);assert.equal(result.data.tasks.length,28);});
