import test from 'node:test'; import assert from 'node:assert/strict';
import { compareGridEvents, expandGridEventRange, normalizeEditableTimeStatus, toGridEventSummary } from '../.test-build/lib/gridModel.js';
import { CORE_COLOR_PALETTE, CORE_COLOR_FAMILIES, normalizedPaletteIsUnique, paletteWithCurrentColor, minimumPaletteCIE76 } from '../.test-build/lib/palette.js';
import { filterTasksByStatus } from '../.test-build/lib/taskWorkflow.js';
import { planProjectTagDeletion } from '../.test-build/lib/projectOperations.js';
import { selectAIExportData, aiExportManifest, sanitizeAIRelationships, validateEventProject } from '../.test-build/lib/releaseContracts.js';
const event=(id,o={})=>({id,date:'2026-01-01',endDate:null,title:id,category:'c1',projectId:null,timeStatus:'all-day',startTime:null,endTime:null,color:'#000',notes:null,displayPriority:4,showInGrid:true,showInExport:true,linkedTaskIds:[],aiNotes:null,sourceNotes:null,...o});
const task=(id,o={})=>({id,name:id,category:'c1',dueDate:null,status:'todo',owner:'',nextAction:null,notes:null,priority:'medium',projectId:null,dueDateType:'someday-backlog',triageStatus:'backlog',parentTaskId:null,linkedEventIds:[],...o});
test('grid comparator honors every tie level and legacy states',()=>{const rank=new Map([['c1',1],['c2',2]]), cmp=compareGridEvents(rank); const values=[event('z',{title:'same',category:'c2'}),event('e',{title:'same',category:'c1'}),event('d',{title:'Beta',category:'c1'}),event('c',{title:'alpha',category:'c1'}),event('b',{timeStatus:'timed',startTime:'10:00'}),event('a',{timeStatus:'approximate',startTime:'09:00'}),event('p',{timeStatus:'timed',startTime:'23:00',displayPriority:1}),event('u',{timeStatus:'unknown',displayPriority:1})]; assert.deepEqual(values.sort(cmp).map(x=>x.id),['p','a','b','u','c','d','e','z']);});
test('inclusive range expansion retains one identity across each grid date',()=>assert.deepEqual(expandGridEventRange(toGridEventSummary(event('e',{date:'2026-02-27',endDate:'2026-03-01'})),2026).map(x=>x.date),['2026-02-27','2026-02-28','2026-03-01']));
test('legacy editor time normalization',()=>{assert.equal(normalizeEditableTimeStatus('approximate'),'timed');assert.equal(normalizeEditableTimeStatus('unknown'),'all-day');});
test('direct event projects count in deletion clear and reassign',()=>{const data={projects:[{id:'p1',name:'One',color:'#000',order:0,aliases:[],status:'active',notes:null},{id:'p2',name:'Two',color:'#000',order:1,aliases:[],status:'active',notes:null}],tasks:[task('t',{projectId:'p1'})],events:[event('e',{projectId:'p1'})],milestones:[]}; assert.equal(planProjectTagDeletion(data,'p1').ok,false); const clear=planProjectTagDeletion(data,'p1','clear'); assert.equal(clear.value.tasks[0].projectId,null);assert.equal(clear.value.events[0].projectId,null); const move=planProjectTagDeletion(data,'p1','reassign','p2');assert.equal(move.value.events[0].projectId,'p2');});
test('event project validation supports canonical null',()=>{assert.equal(validateEventProject(null,new Set()).ok,true);assert.equal(validateEventProject('bad',new Set()).ok,false)});
test('status filter is single-select and combines without sorting',()=>{const ts=[task('a'),task('b',{status:'done'}),task('c',{status:'blocked'})];assert.deepEqual(filterTasksByStatus(ts,'done').map(x=>x.id),['b']);assert.equal(filterTasksByStatus(ts,'all').length,3)});
test('AI complete and range scopes have exact dense counts and manifest',()=>{const data={categories:[{id:'c1',label:'C',color:'#000'}],projects:[{id:'p1'}],people:[{id:'x'}],events:[event('in',{date:'2026-02-01',endDate:'2026-02-03'}),event('out',{date:'2025-01-01'})],personEvents:[{id:'s',person:'x',date:'2026-02-02',endDate:null}],tasks:[task('undone'),task('undated-done',{status:'done'}),task('dated-in',{dueDate:'2026-02-02'}),task('dated-out',{dueDate:'2027-02-02',status:'done'})],milestones:[{id:'m',targetDate:'2026-02-02'},{id:'mo',targetDate:'2027-01-01'}]};assert.equal(selectAIExportData(data).tasks.length,4);const scoped=selectAIExportData(data,{mode:'range',start:'2026-02-01',end:'2026-02-03'});assert.deepEqual([scoped.events.length,scoped.personEvents.length,scoped.tasks.length,scoped.milestones.length],[1,1,3,1]);assert.equal(aiExportManifest(scoped,{mode:'range'}).counts.tasks,3)});
test('AI hard relationships are sanitized on adds and omitted on updates with one warning',()=>{const input={tasks:{add:[task('a',{parentTaskId:'x',linkedEventIds:['e']})],update:[{id:'old',parentTaskId:null,linkedEventIds:[]}]},events:{add:[event('e',{linkedTaskIds:['a']})],update:[{id:'old-e',linkedTaskIds:[]}]}};const out=sanitizeAIRelationships(input);assert.equal(out.warnings.length,1);assert.equal(out.value.tasks.add[0].parentTaskId,null);assert.deepEqual(out.value.events.add[0].linkedTaskIds,[]);assert.equal('linkedTaskIds' in out.value.events.update[0],false)});
test('palette has 32 unique named entries and preserves arbitrary colors',()=>{assert.equal(CORE_COLOR_PALETTE.length,32);assert.equal(CORE_COLOR_FAMILIES.length,32);assert.equal(normalizedPaletteIsUnique(),true);assert.equal(paletteWithCurrentColor('#123456')[0],'#123456');assert.ok(minimumPaletteCIE76() >= 12)});

test('production AI package uses authoritative complete and range scopes', async()=>{
 const {generateUniversalCurrentPackage}=await import('../.test-build/lib/aiPrompt.js');
 const data={categories:[{id:'other',label:'Other',color:'#666'}],projects:[{id:'p',name:'P',color:'#123456',order:0,aliases:[],status:'active',notes:'project note'}],people:[{id:'person',label:'Person',color:'#654321',order:0}],events:[event('cross',{date:'2026-01-30',endDate:'2026-02-02',notes:'user',aiNotes:'ai',sourceNotes:'source'}),event('out',{date:'2025-01-01'})],personEvents:[{id:'sched',person:'person',title:'Schedule',date:'2026-02-02',endDate:'2026-02-04',startTime:null,endTime:null,color:'#000',notes:'schedule'}],tasks:[task('undated',{status:'done',schedulingNotes:'sequence'}),task('in',{dueDate:'2026-02-03'}),task('out-task',{dueDate:'2027-01-01',status:'done'})],milestones:[{id:'m',title:'M',targetDate:'2026-02-03'},{id:'out-m',title:'O',targetDate:'2027-01-01'}]};
 const read=p=>JSON.parse(p.slice(p.lastIndexOf('CURRENT LIFEGRID CONTEXT\n')+'CURRENT LIFEGRID CONTEXT\n'.length));
 const all=read(generateUniversalCurrentPackage(data,{id:'cal',name:'Calendar'},{start:null,end:null}));
 assert.deepEqual(all.manifest.counts,{categories:1,projects:1,people:1,events:2,personEvents:1,tasks:3,milestones:2}); assert.equal(all.tasks[0].schedulingNotes,'sequence');
 const range=read(generateUniversalCurrentPackage(data,{id:'cal',name:'Calendar'},{start:'2026-02-01',end:'2026-02-03'}));
 assert.deepEqual(range.events.map(x=>x.id),['cross']); assert.deepEqual(range.tasks.map(x=>x.id),['undated','in']); assert.deepEqual(range.milestones.map(x=>x.id),['m']); assert.deepEqual(range.manifest.counts,{categories:1,projects:1,people:1,events:1,personEvents:1,tasks:2,milestones:1});
});

test('parseAIUpdate sanitizes hard relationships before preflight and preserves stored links', async()=>{
 const {parseAIUpdate}=await import('../.test-build/lib/aiPrompt.js'); const {preflightPatch}=await import('../.test-build/lib/aiPatchApply.js');
 const data={categories:[{id:'other',label:'Other',color:'#666'}],projects:[],people:[],events:[event('old-e',{category:'other',linkedTaskIds:['old-t']})],tasks:[task('old-t',{category:'other',parentTaskId:'parent',linkedEventIds:['old-e']}),task('parent',{category:'other'})],personEvents:[],milestones:[]};
 const patch=parseAIUpdate(JSON.stringify({lifegridPatchVersion:4,tasks:{add:[task('new',{category:'other',parentTaskId:'missing',linkedEventIds:['missing']})],update:[{id:'old-t',notes:'safe',parentTaskId:'missing',linkedEventIds:['missing']}]},events:{add:[event('new-e',{category:'other',linkedTaskIds:['missing']})],update:[{id:'old-e',notes:'safe',linkedTaskIds:['missing']}]}}),data.categories,data);
 assert.equal(patch.tasks.add[0].parentTaskId,null); assert.deepEqual(patch.tasks.add[0].linkedEventIds,[]); assert.deepEqual(patch.events.add[0].linkedTaskIds,[]); assert.equal('parentTaskId' in patch.tasks.update[0],false); assert.equal(patch.warnings.filter(x=>x.includes('hard relationships')).length,1);
 const plan=preflightPatch(data,patch); assert.equal(plan.findings.some(x=>x.severity==='blocking'),false); assert.equal(plan.data.tasks.find(x=>x.id==='old-t').parentTaskId,'parent'); assert.deepEqual(plan.data.events.find(x=>x.id==='old-e').linkedTaskIds,['old-t']);
});

test('Event project preflight resolves selected dependencies and applies exact result', async()=>{const {preflightPatch,applyPatchAtomically,patchProposalKey}=await import('../.test-build/lib/aiPatchApply.js'); const data={categories:[{id:'other',label:'Other',color:'#666'}],projects:[{id:'existing',name:'Existing',color:'#000',order:0,aliases:[],status:'active',notes:null}],people:[],tasks:[],events:[event('old',{category:'other',projectId:'existing'})],personEvents:[],milestones:[]}; const valid=preflightPatch(data,{events:{update:[{id:'old',projectId:null}]}});assert.equal(valid.findings.some(x=>x.severity==='blocking'),false);assert.equal(valid.data.events[0].projectId,null); const bad=preflightPatch(data,{events:{update:[{id:'old',projectId:'bad'}]}});assert.ok(bad.findings.some(x=>x.severity==='blocking')); const patch={projects:{add:[{id:'new-p',name:'New project',color:'#123456',order:1,aliases:[],status:'active',notes:null}]},events:{add:[event('new-e',{category:'other',projectId:'new-p'})]}};const ok=preflightPatch(data,patch);assert.equal(ok.findings.some(x=>x.severity==='blocking'),false);assert.deepEqual(applyPatchAtomically(data,patch).data,ok.data);const selected=new Set([patchProposalKey('events','add','new-e')]);assert.ok(preflightPatch(data,patch,selected).findings.some(x=>x.severity==='blocking'));});

test('shared day and export expansion include full ranges in comparator order without changing sources', async()=>{const {eventsForDate,expandEventsToDateBuckets}=await import('../.test-build/lib/gridModel.js');const source=[event('all',{date:'2026-02-01',endDate:'2026-02-03'}),event('timed',{date:'2026-02-02',timeStatus:'timed',startTime:'08:00',endTime:'09:00'})],before=structuredClone(source),rank=new Map([['c1',0]]);assert.deepEqual(eventsForDate(source,'2026-02-02',rank).map(x=>x.id),['timed','all']);assert.deepEqual(eventsForDate(source,'2026-02-03',rank).map(x=>x.id),['all']);assert.equal(eventsForDate(source,'2026-02-04',rank).length,0);const buckets=expandEventsToDateBuckets(source,'2026-01-01','2026-12-31',rank);assert.deepEqual(buckets.get('2026-02-02').map(x=>x.id),['timed','all']);assert.deepEqual(source,before);});

test('AI Event time boundary canonicalizes legacy proposals once and preserves untouched legacy updates', async()=>{const {parseAIUpdate}=await import('../.test-build/lib/aiPrompt.js');const {preflightPatch}=await import('../.test-build/lib/aiPatchApply.js');const data={categories:[{id:'other',label:'Other',color:'#666'}],projects:[],people:[],tasks:[],events:[event('legacy',{category:'other',timeStatus:'approximate',startTime:'08:00',endTime:'09:00'})],personEvents:[],milestones:[]};const patch=parseAIUpdate(JSON.stringify({lifegridPatchVersion:4,events:{add:[event('a',{category:'other',timeStatus:'approximate',startTime:'10:00',endTime:'11:00'}),event('u',{category:'other',timeStatus:'unknown',startTime:'10:00',endTime:'11:00'}),{...event('pair',{category:'other',startTime:'12:00',endTime:'13:00'}),timeStatus:undefined},{...event('none',{category:'other'}),timeStatus:undefined}],update:[{id:'legacy',notes:'only'}]}}),data.categories,data);assert.deepEqual(patch.events.add.map(x=>[x.timeStatus,x.startTime,x.endTime]),[['timed','10:00','11:00'],['all-day',null,null],['timed','12:00','13:00'],['all-day',null,null]]);assert.equal(patch.warnings.filter(x=>x.includes('time types were normalized')).length,1);const plan=preflightPatch(data,patch);assert.equal(plan.findings.some(x=>x.severity==='blocking'),false);assert.equal(plan.data.events.find(x=>x.id==='legacy').timeStatus,'approximate');});

test('AI timed additions require a complete pair and explicit updates canonicalize after merge', async()=>{const {parseAIUpdate}=await import('../.test-build/lib/aiPrompt.js');const data={categories:[{id:'other',label:'Other',color:'#666'}],projects:[],people:[],tasks:[],events:[event('old',{category:'other',timeStatus:'approximate',startTime:'08:00',endTime:'09:00'})],personEvents:[],milestones:[]};assert.throws(()=>parseAIUpdate(JSON.stringify({lifegridPatchVersion:4,events:{add:[event('bad',{category:'other',timeStatus:'timed',startTime:'08:00',endTime:null})],update:[]}}),data.categories,data),/Timed events require both/);const timed=parseAIUpdate(JSON.stringify({lifegridPatchVersion:4,events:{add:[],update:[{id:'old',timeStatus:'approximate'}]}}),data.categories,data);assert.equal(timed.events.update[0].timeStatus,'timed');const allDay=parseAIUpdate(JSON.stringify({lifegridPatchVersion:4,events:{add:[],update:[{id:'old',timeStatus:'unknown'}]}}),data.categories,data);assert.deepEqual([allDay.events.update[0].timeStatus,allDay.events.update[0].startTime,allDay.events.update[0].endTime],['all-day',null,null]);});

test('palette foregrounds satisfy WCAG contrast and malformed input is safe', async()=>{const {getReadableTextColor,readableContrastRatio}=await import('../.test-build/lib/palette.js');for(const color of CORE_COLOR_PALETTE)assert.ok(readableContrastRatio(color)>=4.5,`${color} contrast`);assert.equal(getReadableTextColor('#ffffff'),'#000000');assert.equal(getReadableTextColor('#000000'),'#ffffff');for(const color of ['#ffff1a','#1affff','#d6d2a9'])assert.equal(getReadableTextColor(color),'#000000');assert.equal(getReadableTextColor('bad'),'#ffffff');});

test('targeted export buckets clip spanning Events at both boundaries in comparator order', async()=>{const {expandEventsToDateBuckets}=await import('../.test-build/lib/gridModel.js');const source=[event('before',{date:'2026-01-30',endDate:'2026-02-02'}),event('after',{date:'2026-02-03',endDate:'2026-02-09'}),event('cover',{date:'2026-01-01',endDate:'2026-12-31',displayPriority:5}),event('timed',{date:'2026-02-03',timeStatus:'timed',startTime:'09:00',endTime:'10:00'})],before=structuredClone(source),b=expandEventsToDateBuckets(source,'2026-02-01','2026-02-05',new Map([['c1',0]]));assert.deepEqual(b.get('2026-02-01').map(x=>x.id),['before','cover']);assert.deepEqual(b.get('2026-02-03').map(x=>x.id),['timed','after','cover']);assert.deepEqual(b.get('2026-02-05').map(x=>x.id),['after','cover']);assert.equal(b.has('2026-01-31'),false);assert.deepEqual(source,before);});
