import test from 'node:test'; import assert from 'node:assert/strict';
import { EXPORT_PRESETS, createDefaultExportDraft, choosePublicationLayout, choosePublicationOrientation, isExactCalendarMonth, LETTER_FRAME } from '../.test-build/lib/operationalExport.js';
import { resolveExportDateRange } from '../.test-build/lib/gridAwareness.js';
import { planGridPublication } from '../.test-build/lib/gridPublicationPlan.js';
test('v0.5.30 presets have exact operational order and no fiscal labels',()=>{assert.deepEqual(EXPORT_PRESETS.map(x=>x[1]),['Current Grid','Calendar Year','CY Q1','CY Q2','CY Q3','CY Q4','CY Current Month','Next 30','Next 14','Next 7','Today','Custom']);assert.ok(!EXPORT_PRESETS.flat().some(x=>/Fiscal|FY/.test(x)));});
test('fresh drafts reset every session',()=>{const a=createDefaultExportDraft(),b=createDefaultExportDraft();a.selectedCategoryIds.push('x');assert.deepEqual(b,{datePreset:'currentGrid',customStart:'',customEnd:'',categoryMode:'all',selectedCategoryIds:[],projectId:'all',theme:'light',includeGeneratedAt:true,customTitle:'',customSubtitle:''});});
test('local today and current month ranges are deterministic including leap year',()=>{assert.deepEqual(resolveExportDateRange('today',{start:'x',end:'x'},2026,'2026-08-31'),{start:'2026-08-31',end:'2026-08-31'});assert.deepEqual(resolveExportDateRange('currentMonth',{start:'x',end:'x'},2024,'2024-02-12'),{start:'2024-02-01',end:'2024-02-29'});});
test('layout routing boundaries',()=>{for(const n of [7,14,30,45]) assert.equal(choosePublicationLayout('custom','2026-01-01',new Date(Date.UTC(2026,0,n)).toISOString().slice(0,10)),'rolling-day-grid');assert.equal(choosePublicationLayout('custom','2026-01-01','2026-01-01'),'day-agenda');assert.equal(choosePublicationLayout('custom','2026-09-01','2026-09-30'),'month-matrix');assert.ok(isExactCalendarMonth('2026-09-01','2026-09-30'));for(const end of ['2026-03-01','2026-04-30']) assert.equal(choosePublicationLayout('custom','2026-01-01',end),'month-columns');for(const preset of ['currentGrid','calendarYear','q1','q2','q3','q4']) assert.equal(choosePublicationLayout(preset,'2026-01-01','2026-12-31'),'month-columns');});
test('letter frames and orientation',()=>{assert.ok(Math.abs(LETTER_FRAME.portrait.width/LETTER_FRAME.portrait.height-8.5/11)<.001);assert.ok(Math.abs(LETTER_FRAME.landscape.width/LETTER_FRAME.landscape.height-11/8.5)<.001);assert.equal(choosePublicationOrientation('day-agenda',16),'portrait');assert.equal(choosePublicationOrientation('day-agenda',17),'landscape');assert.equal(choosePublicationOrientation('rolling-day-grid',0),'landscape');});
test('Canvas2D consumes semantic agenda layout and wraps legend labels',async()=>{const {readFile}=await import('node:fs/promises');const renderer=await readFile(new URL('../src/lib/gridImageRenderer.ts',import.meta.url),'utf8');assert.match(renderer,/"day-agenda" \| "rolling-day-grid" \| "month-matrix" \| "month-columns"/);assert.match(renderer,/options\.layout === "day-agenda"/);assert.match(renderer,/article\[data-publication-event=/);assert.match(renderer,/data-publication-agenda-time/);const legendBlock=renderer.slice(renderer.indexOf("header.querySelectorAll<HTMLElement>('[data-publication-legend-entry=\"true\"]')"),renderer.indexOf('const empty'));assert.match(legendBlock,/wrapCanvasText/);assert.doesNotMatch(legendBlock,/fitText\(label/);});
test('month matrix headings and scoped export themes are explicit',async()=>{const {readFile}=await import('node:fs/promises');const grid=await readFile(new URL('../src/pages/GridView.tsx',import.meta.url),'utf8');const css=await readFile(new URL('../src/index.css',import.meta.url),'utf8');assert.match(grid,/DOW_HEADINGS = \["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"\]/);assert.match(grid,/publicationPlan\.layout === 'month-matrix'[\s\S]*DOW_HEADINGS/);assert.match(css,/\[data-publication-theme="light"\]/);assert.match(css,/\[data-publication-theme="dark"\]/);});
test('month-column inline surfaces use effective publication theme',async()=>{const {readFile}=await import('node:fs/promises');const grid=await readFile(new URL('../src/pages/GridView.tsx',import.meta.url),'utf8');assert.match(grid,/effectivePublicationTheme = monthPublication \? exportTheme : theme/);const monthCells=grid.slice(grid.indexOf('if (day > maxDay'),grid.indexOf('</tbody>',grid.indexOf('if (day > maxDay')));assert.match(monthCells,/effectivePublicationTheme === "dark"/);assert.doesNotMatch(monthCells,/(?<!Publication)theme === "dark"/);});

test('DST-spanning 45 and 46 day routing is date-only',()=>{assert.equal(choosePublicationLayout('custom','2026-03-01','2026-04-14'),'rolling-day-grid');assert.equal(choosePublicationLayout('custom','2026-03-01','2026-04-15'),'month-columns');});
test('planner width follows agenda orientation before typography and feasibility',()=>{const records=count=>new Map([['2026-08-31',Array.from({length:count},(_,i)=>({title:`Event ${i}`}))]]);const sparse=planGridPublication({preset:'today',start:'2026-08-31',end:'2026-08-31',recordsByDate:records(16),legendLabels:['A long represented Category']});const dense=planGridPublication({preset:'today',start:'2026-08-31',end:'2026-08-31',recordsByDate:records(17),legendLabels:['A long represented Category']});assert.equal(sparse.orientation,'portrait');assert.equal(sparse.cssWidth,LETTER_FRAME.portrait.width);assert.equal(dense.orientation,'landscape');assert.equal(dense.cssWidth,LETTER_FRAME.landscape.width);assert.ok(sparse.legendEstimatedRows>0);assert.ok(dense.legendEstimatedRows>0);});
test('GridView routes capture from the planner and always builds seven rolling headings',async()=>{const {readFile}=await import('node:fs/promises');const grid=await readFile(new URL('../src/pages/GridView.tsx',import.meta.url),'utf8');assert.match(grid,/usesTargetedPublication = publicationPlan\.layout !== 'month-columns'/);assert.doesNotMatch(grid,/isTargetedDateExport|daysBetweenInclusive/);assert.match(grid,/Array\.from\(\{ length: 7 \}/);assert.match(grid,/day-agenda-heading/);assert.match(grid,/WebkitLineClamp:publicationPlan\.eventTitleLines/);});
test('publication theme scopes every token used by publication accents',async()=>{const {readFile}=await import('node:fs/promises');const css=await readFile(new URL('../src/index.css',import.meta.url),'utf8');for(const scope of ['light','dark']){const block=css.slice(css.indexOf(`[data-publication-theme=\"${scope}\"]`),css.indexOf('}',css.indexOf(`[data-publication-theme=\"${scope}\"]`)));for(const token of ['--background','--foreground','--border','--card','--card-foreground','--muted','--muted-foreground','--primary','--primary-foreground','--ring'])assert.match(block,new RegExp(token));}});
