import test from 'node:test'; import assert from 'node:assert/strict';
import { buildIcsExport, foldIcsLine } from '../.test-build/lib/icsExport.js';
const app={categories:[{id:'work',label:'Work, Team',color:'#000'}]};
const e=(x={})=>({id:'e1',date:'2026-12-31',endDate:'2027-01-01',title:'Plan, review; \\ notes',category:'work',startTime:'09:00',endTime:'10:00',timeStatus:'timed',timeZoneMode:'zoned',timeZone:'America/New_York',notes:'One\r\ntwo',...x});
const out=(x={},o={})=>buildIcsExport(app,[e(x)],{now:new Date('2026-01-02T03:04:05Z'),...o});
test('writes VCALENDAR and VEVENT wrappers',()=>assert.match(out(),/^BEGIN:VCALENDAR[\s\S]*BEGIN:VEVENT[\s\S]*END:VEVENT[\s\S]*END:VCALENDAR\r\n$/));
test('writes stable UID',()=>assert.match(out(),/UID:e1@lifegrid/));
test('writes deterministic DTSTAMP',()=>assert.match(out(),/DTSTAMP:20260102T030405Z/));
test('writes zoned TZID values',()=>assert.match(out(),/DTSTART;TZID=America\/New_York:20261231T090000/));
test('UTC mode converts zoned value',()=>assert.match(out({}, {timeMode:'utc'}),/DTSTART:20261231T140000Z/));
test('UTC mode preserves floating values',()=>assert.match(out({timeZoneMode:'floating',timeZone:null},{timeMode:'utc'}),/DTSTART:20261231T090000/));
test('all-day has exclusive end date across year',()=>assert.match(out({timeStatus:'all-day',startTime:null,endTime:null,timeZone:null,timeZoneMode:null}),/DTEND;VALUE=DATE:20270102/));
test('unknown is included and marked by default',()=>assert.match(out({timeStatus:'unknown',startTime:null,endTime:null,timeZone:null,timeZoneMode:null}),/LifeGrid status: Time unknown/));
test('unknown inclusion has marker',()=>assert.match(out({timeStatus:'unknown',startTime:null,endTime:null,timeZone:null,timeZoneMode:null},{includeUnknown:true}),/X-LIFEGRID-TIME-UNKNOWN:TRUE/));
test('approximate is included and marked by default',()=>assert.match(out({timeStatus:'approximate'}),/LifeGrid status: Approximate time/));
test('approximate inclusion has marker',()=>assert.match(out({timeStatus:'approximate'},{includeApproximate:true}),/X-LIFEGRID-APPROXIMATE:TRUE/));
test('escapes text and normalizes CRLF',()=>assert.match(out(),/SUMMARY:Plan\\, review\\; \\\\ notes[\s\S]*DESCRIPTION:One\\ntwo/));
test('emits category and never location',()=>{assert.match(out(),/CATEGORIES:Work\\, Team/);assert.equal(out().includes('LOCATION'),false)});
test('folds long ASCII lines to 75 octets',()=>assert.ok(foldIcsLine(`SUMMARY:${'a'.repeat(200)}`).every(x=>Buffer.byteLength(x)<=75)));
test('folds UTF-8 without splitting code points',()=>{const lines=foldIcsLine(`SUMMARY:${'😀'.repeat(40)}`);assert.ok(lines.every(x=>Buffer.byteLength(x)<=75));assert.equal(lines.join('').replace(/ /g,''),`SUMMARY:${'😀'.repeat(40)}`)});
test('uses CRLF consistently',()=>assert.equal(out().replace(/\r\n/g,'').includes('\n'),false));
