import test from 'node:test'; import assert from 'node:assert/strict';
import { eventProjectTags, findProjectTagOptions, normalizeAliases, planProjectTagDeletion, projectTagQuickCreateValidation, projectTagUsage, validateProjectTag } from '../.test-build/lib/projectOperations.js';
const projects=[{id:'a',name:'Alpha',color:'#111',aliases:['First'],order:1,status:'active',notes:null},{id:'b',name:'Beta',color:'#222',aliases:[],order:0,status:'archived',notes:null}];
const tasks=[{id:'t1',projectId:'a',status:'todo'},{id:'t2',projectId:'a',status:'done'},{id:'t3',projectId:'b',status:'todo'}]; const events=[{id:'e1',linkedTaskIds:['t1','t2']},{id:'e2',linkedTaskIds:['t1','t3']},{id:'e3',linkedTaskIds:['missing']}];
test('Project Tag normalization validates names and aliases without mutating inputs',()=>{const source=[' Alpha ','ALPHA',''];assert.deepEqual(normalizeAliases(source),['alpha']);assert.deepEqual(source,[' Alpha ','ALPHA','']);assert.equal(validateProjectTag({name:'  alpha ',color:'#111',aliases:[]},projects).ok,false);assert.equal(validateProjectTag({name:' ',color:'#111',aliases:[]},projects).ok,false);assert.equal(validateProjectTag({name:'Gamma',color:'#111',aliases:['first']},projects).ok,false);const good=validateProjectTag({name:' Gamma ',color:'#111',aliases:[' G ','g ']},projects);assert.equal(good.ok,true);if(good.ok)assert.deepEqual(good.value.aliases,['g']);});
test('usage and event derivation are deterministic and deduplicate event links',()=>{const before=JSON.stringify({projects,tasks,events});const usage=projectTagUsage(projects,tasks,events);assert.deepEqual(usage.a,{openTasks:1,completedTasks:1,totalTasks:2,relatedEvents:2});assert.equal(usage.b.relatedEvents,1);assert.deepEqual(eventProjectTags(events[1],tasks,projects).map(p=>p.id),['b','a']);assert.equal(JSON.stringify({projects,tasks,events}),before);});
test('archived tags are excluded from new assignment but retained on an existing task',()=>{assert.deepEqual(findProjectTagOptions(projects,'',null).map(p=>p.id),['a']);assert.deepEqual(findProjectTagOptions(projects,'', 'b').map(p=>p.id),['b','a']);assert.deepEqual(findProjectTagOptions(projects,'first').map(p=>p.id),['a']);});
test('selector search is trimmed, case insensitive, ordered, and supports quick-create guards',()=>{const before=JSON.stringify(projects);assert.deepEqual(findProjectTagOptions(projects,' FIRST ').map(p=>p.id),['a']);assert.deepEqual(findProjectTagOptions(projects,'',null,true).map(p=>p.id),['b','a']);assert.equal(projectTagQuickCreateValidation('',projects).ok,false);assert.equal(projectTagQuickCreateValidation(' alpha ',projects).ok,false);assert.equal(projectTagQuickCreateValidation('First',projects).ok,false);const valid=projectTagQuickCreateValidation(' Gamma ',projects);assert.equal(valid.ok,true);if(valid.ok)assert.equal(valid.value.name,'Gamma');assert.equal(JSON.stringify(projects),before);});
test('deletion plans validate atomically, preserve events, and block legacy milestones',()=>{const base={projects,tasks,events,milestones:[]};assert.equal(planProjectTagDeletion(base,'a').ok,false);const clear=planProjectTagDeletion(base,'a','clear');assert.equal(clear.ok,true);if(clear.ok){assert.equal(clear.value.tasks[0].projectId,null);assert.deepEqual(clear.value.events,events);assert.equal(clear.value.projects.some(p=>p.id==='a'),false);}assert.equal(planProjectTagDeletion(base,'a','reassign','b').ok,false);const active=[...projects,{...projects[1],id:'c',status:'active'}];const reassigned=planProjectTagDeletion({...base,projects:active},'a','reassign','c');assert.equal(reassigned.ok,true);if(reassigned.ok)assert.equal(reassigned.value.tasks[0].projectId,'c');assert.equal(planProjectTagDeletion({...base,milestones:[{id:'m',projectId:'a'}]},'a','clear').ok,false);});
